### ISSUE TITLE
Null value for $.viewer.message_threads.sync_sequence_id still(/again?) in 1.1.0 with bitlbee 3.5.1

### ISSUE THREAD

**Issue by srhb** [bitlbee/bitlbee-facebook#148]
The previous issue is locked, so posting anew:

    facebook - Logging in: Authenticating
    facebook - Logging in: Fetching contacts
    facebook - Logging in: Connecting
    facebook - Login error: Null value for $.viewer.message_threads.sync_sequence_id
    facebook - Logging in: Signing off..

This is with an app password, and contacts initially do start appearing. Bitlbee is version 3.5.1 and bitlbee-facebook 1.1.0 which, as I read the release notes, should include the fix for #138

How can I help?

**Comment by dequis** [comment]
When was the last time this worked?

**Comment by srhb** [comment]
No more than a few days ago, I believe. Unfortunately I don't have logs from then.

**Comment by dequis** [comment]
Output of 'plugins' command?

**Comment by srhb** [comment]
Plugin                          Version
    facebook                        1.1.0

    Enabled Protocols: facebook, hipchat, identica, jabber, msn, oscar, twitter

**Comment by BlackLight** [comment]
The issue replicates in my environment as well

**Comment by michalrus** [comment]
+1, this just started happening here.

**Comment by dequis** [comment]
Since I still can't reproduce this issue but purple-facebook users don't seem to have it, my best guess is that it's related to the user agent change I did over there but not here.

To figure out if it really matters I pushed a commit (8bbf163cfb796524754d7872e148c9793cd4452f) with an experimental hidden "tweak" setting. It allows values between 0 and 15, some of them redundant. More details in the commit log.

The default value shouldn't change anything, but please report if it does.

To test, disconnect the account, change the tweak setting and reconnect:

```
account facebook off
account facebook set tweak 1
account facebook on
```

Please repeat the same thing with values 1, 2, 3, 7 and 11. Report any differences with each.

If it says the setting doesn't exist, you're not running the last commit.

**Comment by michalrus** [comment]
Awesome, I'll provide test results later today, traveling now. 😊

As a means to repro this, please send 20+ messages to someone at once, w/o
throttling. This started happening to me after I accidentally pasted my
clipboard to a friend. FB killed the connection and now this happens right
after receiving the buddy list.

**Comment by khoi-nguyen** [comment]
Hi everyone,

I had the same issue, but I just needed to upgrade to 1.1.1.

Hope this helps someone.

**Comment by dequis** [comment]
Hahah oh wow. I totally forgot 1.1.1 was a thing, got projects mixed up. Shit. Thanks for pointing that out. And here I was thinking this was yet another issue.

Yes, that should fix it, already got confirmation from other users before.

**Comment by srhb** [comment]
I'm very sorry about that. I misunderstood the changelog, and thought 1.1.1 was completely unrelated to this problem, so I didn't even test it. I did now, and it works like a charm. Sorry for the noise.
