### ISSUE TITLE
Support muted conversations

### ISSUE THREAD

**Issue by gregf** [bitlbee/bitlbee-facebook#167]
If I mute a conversation  in Facebook, I should no longer receive group messages.

**Comment by dgw** [comment]
I'm not sure this would be a good thing. If you mute a conversation in Facebook, you still get the messages (just not the notifications). If you stopped getting the messages in BitlBee for muted conversations, you wouldn't get the messages through BitlBee ever and would have to check the FB website or app for muted conversations later. (Or bitlbee-facebook would need a new command to "catch up" a muted conversation and fetch missed messages, but that could get tricky on both implementation and UX.)

Probably best to just make sure your IRC client is set up in such a way that it doesn't bother you if it gets new messages in a channel that don't highlight or otherwise grab attention—or even disable highlights in Facebook chat channels, if supported.

**Comment by gregf** [comment]
I agree. I thought thought they worked a bit different than they do I guess. Thanks.
