### ISSUE TITLE
Can you rename groupchat channel name?

### ISSUE THREAD

**Issue by yimmt** [bitlbee/bitlbee-facebook#193]
This is particularly an issue when you set group_chat_open to all and then the channel name you join is #chat_000. Is there a way to rename this channel, and save it?

**Comment by liskin** [comment]
Yes, you can create a named channel for it. Send `channel #chat_000 set` to the control channel, and note the `room` value. Then send `chat add facebook <room> #something` and that'll create a permanent channel named `#something`. You might also want to do `channel #something set auto_join true`(it might be the default, I don't remember).

**Comment by yimmt** [comment]
@liskin 
I closed this without trying. When I do `channel #chat_000 set`, the `room` value is empty. I believe I can't set it manually without looking at facebook directly to get the value. Are you suggesting me to go to facebook to get the value so I can rename it? Is there a way to do it without going to facebook?

**Comment by liskin** [comment]
@yimmt Oh, I'm sorry, I didn't remember the exact steps I used as it's been a while since I last had to do this. So here's another thing you can try:

When bitlbee puts me in the `#chat_000` channel, it sets to topic to something like `BitlBee groupchat: "1979775053384323". Please keep in mind that root-commands wo
n't work here. Have fun!` and then it changes it to the list of people or the groupchat name. The original topic should be visible in your IRC client, though, so use that number as `room`.
